<a href="https://colab.research.google.com/github/Optimus0205/Computer-Vision/blob/main/4_CNN_Basic(Grey%2BRGB_Channel).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##CNN from Scratch

In [ ]:
import numpy as np

# Define a simple 5X5 Grayscale image
img=np.array([
    [1, 2, 3, 0, 1],
    [0, 1, 2, 3, 2],
    [3, 0, 1, 2, 1],
    [2, 1, 3, 0, 0],
    [1, 2, 0, 1, 2]
])

img.shape

(5, 5)

In [ ]:
# Define a 3X3 Kernel
k=np.array([
    [0, 1, 0],
    [1, -4, 1],
    [0, 1, 0]
])

k.shape

(3, 3)

In [ ]:
# Defining operation
def convolue(img,k):
  img_h, img_w = img.shape
  k_h, k_w = k.shape

  output_h = img_h - k_h + 1
  output_w = img_w - k_w + 1

  output = np.zeros((output_h, output_w))

  for i in range(output_h):
    for j in range(output_w):
      output[i,j] = np.sum(img[i:i+k_h, j:j+k_w] * k)

  return output

In [ ]:
#Result

output=convolue(img,k)
print('Convolutional Output : \n',output)

Convolutional Output : 
 [[  0.   0.  -6.]
 [  6.   3.  -3.]
 [  3. -10.   6.]]


In [ ]:
5-3+1,5-3+1

(3, 3)

## Padding with stride = 1

In [ ]:
# Adding padding
def pad_img(img, pad):
  return np.pad(img, pad, mode='constant', constant_values=0)  #zero-padding


In [ ]:
pad_img(img,1)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0, 1, 0],
       [0, 0, 1, 2, 3, 2, 0],
       [0, 3, 0, 1, 2, 1, 0],
       [0, 2, 1, 3, 0, 0, 0],
       [0, 1, 2, 0, 1, 2, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [ ]:
def convolue_with_padding_and_stride(img,k, stride=1, padding=0):
  if padding > 0:
    img=pad_img(img,padding)

  img_h, img_w = img.shape
  k_h, k_w = k.shape

  output_h = (img_h - k_h)//stride+1
  output_w = (img_w - k_w)//stride+1

  output = np.zeros((output_h, output_w))

  for i in range(output_h):
    for j in range(output_w):
      output[i//stride,j//stride] = np.sum(img[i:i+k_h, j:j+k_w] * k)

  return output

In [ ]:
padded_output=convolue_with_padding_and_stride(img,k,stride=1,padding=1)
print('Padded Convolue Output: \n', padded_output)

Padded Convolue Output: 
 [[ -2.  -3.  -8.   7.  -2.]
 [  5.   0.   0.  -6.  -3.]
 [-10.   6.   3.  -3.   0.]
 [ -3.   3. -10.   6.   3.]
 [  0.  -6.   6.  -2.  -7.]]


## Max Pooling

In [ ]:
def max_pooling(img,pool_size,stride):
  img_h, img_w = img.shape

  output_h = (pool_size)//stride+1
  output_w = (pool_size)//stride+1

  output = np.zeros((output_h, output_w))

  for i in range(0, output_h*stride,stride):
    for j in range(0, output_w*stride,stride):
      output[i//stride,j//stride]=np.max(img[i:i+pool_size, j:j+pool_size])                                 #.max -> max,  .min -> min,   .avg -> avg

  return output

In [ ]:
pooled_output=max_pooling(img, pool_size=2, stride=2)
print('Max Pooling Output : \n', pooled_output)

Max Pooling Output : 
 [[2. 3.]
 [3. 3.]]


# Convolution on RGB Images

In [ ]:
import numpy as np

# Defining a 5X5X3 RGB image (3 channels)
img=np.array([
    [[1, 0, 2], [2, 1, 1], [3, 2, 0], [0, 1, 1], [1, 0, 2]],
    [[0, 1, 0], [1, 0, 1], [2, 2, 2], [3, 1, 3], [2, 0, 1]],
    [[3, 0, 2], [0, 1, 0], [1, 0, 1], [2, 2, 2], [1, 0, 0]],
    [[2, 1 ,1], [1, 0, 2], [3, 3, 1], [0, 1, 0], [0, 2, 1]],
    [[1, 2, 2], [2, 1, 0], [0, 0, 1], [1, 2, 2], [2, 1, 1]]
])
img.shape

(5, 5, 3)

In [ ]:
# Define a 3X3X3 filter kernel for each channel (RGB)
k=np.array([
    [[0, 1, 0], [1, -1, 1], [0, 1, 0]],
    [[1, 0, 1], [0, -1, 0], [1, 0, 1]],
    [[0, 1, 0], [1, 1, 1], [0, 1, 0]]
])
k.shape

(3, 3, 3)

In [ ]:
# Defining operation
def convolue_rgb(img,k):
  img_h, img_w,img_c = img.shape
  k_h, k_w,k_c = k.shape

  output_h = img_h - k_h + 1
  output_w = img_w - k_w + 1

  output = np.zeros((output_h, output_w, 1))

  for m in range(img_c):
    for i in range(output_h):
      for j in range(output_w):
        output[i,j] = np.sum(img[i:i+k_h, j:j+k_w, m] * k)

    return output

In [ ]:
output=convolue_rgb(img,k)
print('Convolutional Output : \n',output)

Convolutional Output : 
 [[[15.]
  [18.]
  [15.]]

 [[19.]
  [18.]
  [15.]]

 [[18.]
  [ 6.]
  [16.]]]


# Implementing Via Keras

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, models

# Example input shape for a 32X32 RGB image
input_shape=(100,100,3)

# Define the model
model=models.Sequential()

# Add input layers
model.add(layers.Input(shape=input_shape))

# Adding Convolutional layer
model.add(layers.Conv2D(16, (3,3), padding='same', strides=1, activation='relu'))

# Adding Max Pooling Layer
model.add(layers.MaxPooling2D(pool_size=(2,2), strides=2))

# Adding more convolution and pooling layers as needed
model.add(layers.Conv2D(32, (3,3), padding='same', strides=1, activation='relu'))
model.add(layers.MaxPooling2D(pool_size=(2,2), strides=2))

# Print model summary to see the structure
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_6 (Conv2D)               │ (None, 100, 100, 16)   │           448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 50, 50, 16)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 50, 50, 32)     │         4,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 25, 25, 32)     │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,088 (19.88 KB)

 Trainable params: 5,088 (19.88 KB)

 Non-trainable params: 0 (0.00 B)